name: Zhlubb
favicon: null
layout_spectrum: 0.05383639968931675
typography_spectrum: 0.6871353343594819
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.037018913542851806
  lightness: 0.6203766481485218
  saturation: 0.4000457643996924
  rhythmicContrast: 0.8859803376253694
purpose: []
